using System;
using System.Collections.Generic;

namespace DemoWebAPI.Models
{
    public partial class Claims
    {
        public decimal ClaimId { get; set; }
        public string UrlNo { get; set; }
        public string AltUrilNo { get; set; }
        public string ClaimType { get; set; }
        public string LocNo { get; set; }
        public string GroupCode { get; set; }
        public decimal ClaimantId { get; set; }
        public decimal EmployeeId { get; set; }
        public string InsCoId { get; set; }
        public decimal? HospitalId { get; set; }
        public DateTime? CfRecvdDate { get; set; }
        public string HBillNo { get; set; }
        public DateTime? HBillDate { get; set; }
        public DateTime? HBillRecvdDate { get; set; }
        public DateTime? Doa { get; set; }
        public DateTime? Dod { get; set; }
        public decimal? TotAmtClaimed { get; set; }
        public decimal? TotAmtApproved { get; set; }
        public DateTime? CfSendToCaDate { get; set; }
        public string CaeName { get; set; }
        public DateTime? CfSentToDrDate { get; set; }
        public DateTime? DrrCompDate { get; set; }
        public string DrRemark { get; set; }
        public DateTime? CompCfRecvdFromCaDate { get; set; }
        public DateTime? CfSentToInsDate { get; set; }
        public decimal? AmtClaimedEmp { get; set; }
        public decimal? AmtClaimedHosp { get; set; }
        public decimal? TotAmtClaimedIns { get; set; }
        public decimal? AmtPayableEmp { get; set; }
        public decimal? AmtPayableHosp { get; set; }
        public decimal? TotAmtPassedIns { get; set; }
        public DateTime? PayRecvdFromInsDate { get; set; }
        public decimal? AmtDisallowedByIns { get; set; }
        public string ChqNoIns { get; set; }
        public string ClaimNoIns { get; set; }
        public DateTime? ChqSentToCaDate { get; set; }
        public string ClaimRemarks { get; set; }
        public DateTime? EntryDt { get; set; }
        public string EntryBy { get; set; }
        public DateTime? UpdateDt { get; set; }
        public string UpdateBy { get; set; }
        public decimal? DiagId { get; set; }
        public string InsCoDiv { get; set; }
        public string ClaimDiag { get; set; }
        public string ProceId { get; set; }
        public string ClaimNo { get; set; }
        public string HBillYn { get; set; }
        public decimal? BillDetailId { get; set; }
        public string LotNo { get; set; }
        public DateTime? ChqDate { get; set; }
        public decimal? BankId { get; set; }
        public string DnPrnFlag { get; set; }
        public string DnGenFlag { get; set; }
        public string CrsPrnFlag { get; set; }
        public string CrsPrnStat { get; set; }
        public string DnaPrnFlag { get; set; }
        public string DnaGenFlag { get; set; }
        public string InsChqPayableTo { get; set; }
        public string ChqSentToAccts { get; set; }
        public DateTime? ChqSentToAcctsDt { get; set; }
        public string ChqSentToAcctsBy { get; set; }
        public string ChqRecdAtAccts { get; set; }
        public DateTime? ChqRecdAtAcctsDt { get; set; }
        public string ChqRecdAtAcctsBy { get; set; }
        public string PartialPay { get; set; }
        public string TypeOfBill { get; set; }
        public string ScanBy { get; set; }
        public DateTime? ScanStartDt { get; set; }
        public DateTime? ScanEndDt { get; set; }
        public DateTime? EntryEndDt { get; set; }
        public string DrBy { get; set; }
        public string QCheckBy { get; set; }
        public DateTime? QCheckStartDt { get; set; }
        public DateTime? QCheckEndDt { get; set; }
        public string SentToBrBy { get; set; }
        public DateTime? SentToBrStartDt { get; set; }
        public DateTime? SentToBrEndDt { get; set; }
        public string SentToInsBy { get; set; }
        public DateTime? ClaimsSheetStartDt { get; set; }
        public DateTime? ClaimsSheetEndDt { get; set; }
        public string ClaimsSheetEntredBy { get; set; }
        public string InsQueryBy { get; set; }
        public DateTime? InsQueryStartDt { get; set; }
        public DateTime? InsQueryEndDt { get; set; }
        public string CaseType { get; set; }
        public string KpiIncludeYn { get; set; }
        public string OpenStatus { get; set; }
        public string OpenEnteredBy { get; set; }
        public DateTime? OpenEnteredOn { get; set; }
        public string ClosedStatus { get; set; }
        public string ClosedBy { get; set; }
        public DateTime? ClosedOn { get; set; }
        public string ClaimDiagIcd10 { get; set; }
        public string PaySent { get; set; }
        public DateTime? ActCaStartDt { get; set; }
        public int? DrPenReason { get; set; }
        public string DrEmail { get; set; }
        public string CcHelpDesk { get; set; }
        public DateTime? DrMailDt { get; set; }
        public string Remarks { get; set; }
        public string IpqYn { get; set; }
        public DateTime? IpqStartDt { get; set; }
        public DateTime? IpqEndDt { get; set; }
        public string IpqBy { get; set; }
        public string AuditBy { get; set; }
        public DateTime? AuditStartDt { get; set; }
        public DateTime? AuditEndDt { get; set; }
        public string AddRemarks { get; set; }
        public string AccountNo { get; set; }
        public string MiniShop { get; set; }
        public string PayApprBy { get; set; }
        public DateTime? PayApprDt { get; set; }
        public string PayReportBy { get; set; }
        public DateTime? PayReportDt { get; set; }
        public string OnholdBy { get; set; }
        public DateTime? OnholdStartDt { get; set; }
        public DateTime? OnholdEndDt { get; set; }
        public string OnholdRemarks { get; set; }
        public int? PrevClaimantId { get; set; }
        public int? PrevEmployeeId { get; set; }
        public string UpdateStatus { get; set; }
        public string MiniShop1 { get; set; }
        public string OnholdUpdatedBy { get; set; }
        public DateTime? OnholdUpdatedDt { get; set; }
        public int? CaseId { get; set; }
        public decimal? TdsAmount { get; set; }
        public string TdsRcvdFlag { get; set; }
        public DateTime? TdsAmountRcvdDate { get; set; }
        public DateTime? TdsFileGenDate { get; set; }
        public string InsClaimNo { get; set; }
        public DateTime? SchInsDate { get; set; }
        public decimal? CfClaimedAmt { get; set; }
        public decimal? TdsPercentage { get; set; }
        public DateTime? InsIntiDt { get; set; }
        public DateTime? PrevInsIntiDt { get; set; }
        public string InvoiceNo { get; set; }
        public string VoucherNo { get; set; }
        public string DoctrName { get; set; }
        public string DoctrRegNo { get; set; }
        public string DoctrSpec { get; set; }
        public string HospAcceptanceFlag { get; set; }
        public DateTime? HospAccepFlagDt { get; set; }
        public int? HospAccepFlagUpdatedby { get; set; }
        public DateTime? PayRecvdConfirmDt { get; set; }
        public int? PayRecvdConfirmBy { get; set; }
        public decimal? CopayAmtPaid { get; set; }
        public string ClaimesDeniedFlag { get; set; }
        public string RejectionFlag { get; set; }
        public decimal? ContributionAmt { get; set; }
        public string CappedAilment { get; set; }
        public int? PreviousClaimId { get; set; }
        public string TopupCaseFlag { get; set; }
        public DateTime? InsClaimNoUploadedDt { get; set; }
        public string FactPaySent { get; set; }
        public string FactPayApprBy { get; set; }
        public DateTime? FactPayApprDt { get; set; }
    }
}
