using System;
using System.Collections.Generic;

namespace DemoWebAPI.Models
{
    public partial class Member
    {
        public int MemId { get; set; }
        public int GrpId { get; set; }
        public string GrpCode { get; set; }
        public int? MemCode { get; set; }
        public int MemLocationId { get; set; }
        public int MemDeptId { get; set; }
        public int MemEmpNo { get; set; }
        public string MemAltEmpNo { get; set; }
        public string MemTitle { get; set; }
        public string MemName { get; set; }
        public string MemSex { get; set; }
        public DateTime MemDob { get; set; }
        public DateTime? MemJoinDt { get; set; }
        public int GroupGradeId { get; set; }
        public string MemRelId { get; set; }
        public string MemMartialStatus { get; set; }
        public DateTime? MemMarriageDt { get; set; }
        public string MemRemarks { get; set; }
        public string MemVipFlag { get; set; }
        public string MemLapsedFlag { get; set; }
        public string MemLapsedReason { get; set; }
        public DateTime? MemLapsedDt { get; set; }
        public DateTime? MemUnlapsedDt { get; set; }
        public string MemLapsedRemarks { get; set; }
        public string MemUnlapsedRemarks { get; set; }
        public DateTime? MemLeavingDt { get; set; }
        public DateTime? MemLapsedIntToUhci { get; set; }
        public DateTime? MemLapsedIntToInsCo { get; set; }
        public DateTime? MemLapsedAckRcvdDt { get; set; }
        public decimal? MemTempCoverlevel { get; set; }
        public int? MemMasterlistId { get; set; }
        public int? MemMisId { get; set; }
        public DateTime? MemMisRcvdBoDt { get; set; }
        public DateTime? MemMisRcvdHoDt { get; set; }
        public string MemMisVerifyFlag { get; set; }
        public DateTime? MemMisVerifyDt { get; set; }
        public string MemMisVerifyBy { get; set; }
        public string MemDeleteVerifyFlag { get; set; }
        public DateTime? MemDeleteVerifyDt { get; set; }
        public string MemDeleteVerifyBy { get; set; }
        public string MemMtiFlag { get; set; }
        public DateTime? MemMtiUnflagDt { get; set; }
        public DateTime? MemMtiFlagDt { get; set; }
        public string MemAddAvlFlag { get; set; }
        public string MemBabyOfFlag { get; set; }
        public string MemActiveFlag { get; set; }
        public string MemCreatedBy { get; set; }
        public DateTime MemCreatedDt { get; set; }
        public string MemUpdatedBy { get; set; }
        public DateTime MemUpdatedDt { get; set; }
        public decimal? SybaseMemberId { get; set; }
        public decimal? SybaseCurrentPeriod { get; set; }
        public string MemQcRequired { get; set; }
        public DateTime? MemSpIpReqDt { get; set; }
        public string MemRefundFlag { get; set; }
        public string MemRefundReason { get; set; }
        public string MemAddPdfSent { get; set; }
        public DateTime? MemAddPdfSentDt { get; set; }
        public string MemDelPdfSent { get; set; }
        public DateTime? MemDelPdfSentDt { get; set; }
        public DateTime? MemMasterlistRcvdDt { get; set; }
        public string MemIenrollExpFlag { get; set; }
        public int? MemEntityId { get; set; }
        public int? HlplanTypeId { get; set; }
        public DateTime? MemDot { get; set; }
        public string NameToBePrintedOnIdcard { get; set; }
        public bool? InsuredLastYear { get; set; }
        public int? MemCostCenterId { get; set; }
        public int? MemMailZoneId { get; set; }
        public int? MemRegionId { get; set; }
        public string MemMgrName { get; set; }
        public string MemMgrEmail { get; set; }
        public int? OnlineStatus { get; set; }
        public DateTime? OnlineStatusDate { get; set; }
        public string OnlineStatusBy { get; set; }
        public DateTime? OnlineEnrollmentDt { get; set; }
        public bool? OnlineStatusFlag { get; set; }
        public DateTime? MemDoc { get; set; }
        public int? GrpDesgId { get; set; }
        public string CompGrade { get; set; }
        public string MemPanCard { get; set; }
        public string MemMasterlistRcvdFrm { get; set; }
        public int? OccupationId { get; set; }
        public DateTime? MemSpDolDt { get; set; }
        public string MemParentsDisclaimer { get; set; }
        public DateTime? MemParentsDisclaimerUpdatedDt { get; set; }
        public string MemGrpDisclaimer { get; set; }
        public DateTime? MemGrpDisclaimerUpdatedDt { get; set; }
        public string MemClientGrade { get; set; }
        public string PayGroup { get; set; }
        public string AmexPiEmpId { get; set; }
        public string SpecialStatus { get; set; }
        public string RelExtendedFlag { get; set; }
        public string HrApprFlag { get; set; }
        public string HrApprBy { get; set; }
        public DateTime? HrApprDt { get; set; }
        public string HealthCheckupFlag { get; set; }
        public string ParentsEnrollFor3yr { get; set; }
        public DateTime? ParentsEnrollFor3yrFromDt { get; set; }
        public string GreenFlag { get; set; }
        public bool? AdditionMailFlag { get; set; }
        public string IsDom { get; set; }
        public string IsSelfFunded { get; set; }
        public bool? SummaryForCtsMailFlag { get; set; }
        public string ConfirmFlag { get; set; }
        public string Band { get; set; }
        public string EkId { get; set; }
    }
}
